# Generated by Django 4.2.5 on 2023-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('modeling', models.CharField(blank=True, max_length=255, null=True)),
                ('planimetry', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('software', models.CharField(blank=True, max_length=255, null=True)),
                ('vegetation', models.CharField(blank=True, max_length=255, null=True)),
                ('posproduction', models.CharField(blank=True, max_length=255, null=True)),
                ('type_project', models.CharField(blank=True, max_length=255, null=True)),
                ('description_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('description_4', models.TextField(blank=True, null=True)),
                ('description_5', models.JSONField(blank=True, default=dict, null=True)),
                ('description_6', models.JSONField(blank=True, default=dict)),
                ('media', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
